import Head from 'next/head'
import { Main } from 'src/components/Main/Main'
import { Header } from 'src/components/Header/Header'


 const Home = (props) => {
   return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      {props.isShow ? <h1>{props.count}</h1> : null}
      <button onClick={props.handleClick}>ボタン</button><br/>
      <button onClick={props.handleDisplay}>{props.isShow ? "非表示":"表示"}</button><br/>
      
      <input 
      type="text" 
      value={props.text} 
      onChange={props.handleChange}/><br/>
      <button onClick={props.handleAdd}>追加</button>
      <ul>
        {props.array.map( item => {
         return(<li key={item}>{item}</li>)
        })}
      </ul>
      <Main path="index" 
      />
    </>
  );
}

export default Home;