import Head from 'next/head'
import { Main } from 'src/components/Main/Main'
import { Header } from 'src/components/Header/Header'
import { useCallback  } from 'react';
import { useEffect } from 'react';
import Link from 'next/link';




export default function Home() {
  const foo = 1;

  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    e.preventDefault();
    alert(foo);
  },[]);
  
  useEffect(()=>{
    console.log("マウント時")
    document.body.style.backgroundColor = "lightblue";

    return() =>{
      console.log("アンマウント時")
      document.body.style.backgroundColor = ""; 
    }
  },[])


  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Link
        href='/about' 
        onClick={handleClick}
      >
        ボタン
      </Link>
      <Main path="index" 
      />
    </>
  );
}
